services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    networks:
      - mongo-compose-network

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - '/data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=bugmarker

networks: 
    mongo-compose-network:
      driver: bridge 
    minionetwork:
      driver: bridge
       
volumes:
  mongo_volume:
  minio_volume:
    driver: local


